FROM python:3.8

ARG IMAP_ENV
ARG EMAIL_ENV
ARG PASS_ENV
ARG TOCKEN_TELEGRAN_ENV
ARG CHAT_ID_ENV
ARG DB_ENV
ARG FOLDER_ENV
ARG DOMAIN_ENV

RUN pip install html2text requests  Flask-SQLAlchemy markdown
COPY . /app
WORKDIR /app
EXPOSE 8001
RUN python main.py $IMAP_ENV $EMAIL_ENV $PASS_ENV $TOCKEN_TELEGRAN_ENV $CHAT_ID_ENV $DB_ENV $FOLDER_ENV $DOMAIN_ENV
CMD python main.py